travis:
  secure:
    BINSTAR_TOKEN: pz2W6+wn6rPcK/8Qv9/2dIkX9Yi858n2JANpOeV1bpFtqr9ozXAXTR3UIu8uHBiGeCCspn61kKl0qvAYm1fCKqUVxJwlyI0uGmhNk0zwBlmU7nm7AbLg7oJUG01Ap4lmKsUUMqqJBG/ZE1Db0NzhosKZHJ6Yo6Nx9pFgZ02OzZLoasnQ6A4e1AB0CCck0is04W29hBFq8lWzje7eDqzEkgPZPe71QrCLNYNglGpoPAvrp9WxorGvfP0maZ/3+N2d8pRu5C1NyxwsRJJ9FWDek6l8xkre9koNqNcPEfwWuU199FqBhhOFjPocr1Sua41GC9hKg4AqOZjugeAD9AuqRCiYnVq4e3JfsG5DJjnJ4N0lG06rv8/rmBGClcTkmw0WajegAYVQVDCvHeKPHZ1VxVNxWJctJ4SpYfrcqfqZ6dG/EXJenkbyS11iz6R7NLlJMTjoJ1QfGk1OzLvZwYj+ONVNTO9174bfAg0etCrSEazIo2W40wrVv5sf0AW9+g2x9ThZMQkGNg99uTIGgFNedqo3XIKmDPEUm1xm1ybk6d/cWmwOabKvhRKcpEdKokzsa3hMLc8jgeYRvK5z65odeHwcC0+9AF6rfnZquw5wGKtJ8EOuTVRH/QQ1V3fg0WFx8bPPmAn8W78GA35tBExovEOm2HgB/h5wRmaZTaFAdI8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
